portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve



urlpatterns = [
path('admin/', admin.site.urls),
path('', include('user.urls')),
re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/user/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('',views.indexpage, name='index'),
    path('contact/', views.contactpage,name='contact'),
 ]

portfolio/core/models.py
from django.db import models

# Create your models here.

portfolio/user/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class Website(models.Model):
    name = models.CharField(max_length=100)
    favicon = models.FileField(upload_to='static/icon/', null=True, blank=True,help_text='Upload an SVG file')
    profile_picture = models.ImageField(upload_to='static/image/', null=True, blank=True)

    def __str__(self):
        return self.name
    
class HeroInfo(models.Model):
    AVAILABILITY_CHOICES = [
        ('available', 'Available Now'),
        ('on_holiday', 'On Holiday'),
    ]

    title = models.CharField(max_length=100)  
    availability = models.CharField(
        max_length=20,
        choices=AVAILABILITY_CHOICES,
        default='available', 
    )
    full_name = models.CharField(max_length=200) 
    short_intro = models.TextField(max_length=500)  
    company_name = models.CharField(max_length=200) 
    hireme_link = models.URLField(max_length=500,null=True, blank=True)  
    download_cv_button = models.URLField(max_length=500,null=True, blank=True)  
    long_biography = models.TextField() 

    def __str__(self):
        return self.full_name


class EducationAndTraining(models.Model):
    TRAINING_TYPES = [
        ('trining', 'Trining'),
        ('diploma', 'Diploma'),
        ('certificate', 'Certificate'),
        ('ssc', 'Ssc'),
        ('hsc', 'Hsc'),
        ('bsc', 'Bsc'),
    ]
    
    training_type = models.CharField(max_length=50, choices=TRAINING_TYPES)
    institution_name = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    cgpa = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    year = models.PositiveIntegerField()
    
    def __str__(self):
        return f"{self.training_type} at {self.institution_name} ({self.year})"

class SkillCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return self.name

class MySkill(models.Model):
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE, related_name='skills')
    name = models.CharField(max_length=255)
    icon = models.FileField(upload_to='static/icon/', help_text='Upload an SVG file')

    def __str__(self):
        return self.name


class MyProject(models.Model):
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]
    
    STATUS_CHOICES = [
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]
    
    name = models.CharField(max_length=255)
    difficulty_level = models.CharField(
        max_length=6,
        choices=DIFFICULTY_CHOICES,
        default='medium'
    )
    project_type = models.CharField(max_length=100) 
    logo = models.ImageField(upload_to='static/image/', null=True, blank=True)
    status = models.CharField(max_length=11,choices=STATUS_CHOICES,default='in_progress')
    project_link = models.URLField(max_length=200, null=True, blank=True)
    start_date = models.DateField()
    
    def __str__(self):
        return self.name

class Footer(models.Model):
    title = models.CharField(max_length=255)
    small_talk = models.TextField()
    hire_me_link = models.URLField(max_length=200)
    copyright_text = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    
class SocialIcon(models.Model):
    icon = models.FileField(upload_to='static/icon/', validators=[FileExtensionValidator(allowed_extensions=['svg'])])
    icon_link = models.URLField()

    def __str__(self):
        return self.icon_link

portfolio/user/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

portfolio/core/views.py
from django.shortcuts import render

# Create your views here.

portfolio/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from user.models import *
from django.contrib import messages
from django.core.mail import send_mail
from .forms import *
from django.conf import settings

def indexpage(request):
    hero = HeroInfo.objects.first()
    educations = EducationAndTraining.objects.all().order_by('-id')
    skill_categories = SkillCategory.objects.all()
    projects = MyProject.objects.all().order_by('-id')
    footer = Footer.objects.first() 
    social_icons = SocialIcon.objects.all()
    context = {
        'hero': hero,
        'skill_categories': skill_categories,
        'educations': educations,
        'projects':projects,
        'footer': footer,
        'social_icons': social_icons,
    }
    return render(request, 'index.html', context)

def contactpage(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            subject = f"New Contact Form Submission from {name}"
            body = f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}"

            send_mail(
                subject,
                body,
                settings.DEFAULT_FROM_EMAIL,  
                ["bonyaminshaznuz@gmail.com"],  
                fail_silently=False,
            )

            messages.success(request, "Your message has been sent successfully!")
            return redirect("contact")

    else:
        form = ContactForm()

    return render(request, "contact.html", {"form": form})

portfolio/portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kazi Bony Amin {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    {% if website.favicon %}
    <link rel="icon" type="image/png" href="{{ website.favicon.url }}">
    {% endif %}
</head>

<body>
    {% block content %}
    {% endblock %}

    <script>
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener("click", function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute("href"));
                if (target) {
                    const offset = 120;
                    const top = target.getBoundingClientRect().top + window.scrollY - offset;
                    window.scrollTo({ top, behavior: "smooth" });
                }
            });
        });
    </script>
</body>

</html>

portfolio/portfolio/templates/contact.html
{% extends "base.html" %}

{% block title %}| Contact{% endblock %}

{% block content %}
{% load static %}

<div class="contact-main">
    <a href="javascript:history.back()" class="back-btn"><i class="fas fa-arrow-left"></i></a>

    <div class="container">
        {% if messages %}
            <div class="success-message">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        
        <h1>Contact Me</h1>
        <form action="#" method="POST">
            {% csrf_token %}
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name" required><br><br>

            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" required><br><br>

            <label for="message">Message:</label><br>
            <textarea id="message" name="message" rows="4" required></textarea><br><br>

            <input type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

portfolio/portfolio/templates/footer.html
{% load static %}
<footer>
    <div class="footer-top">
        <h1>{{ footer.title }}</h1>
        <p>{{ footer.small_talk }}</p>
        <div class="footer-contact">
            <a href="{{ footer.hire_me_link }}">Hire Me</a>
            <a href="{% url 'contact' %}">Contact Me</a>
        </div>
    </div>
    <div class="footer-middle">
        <div class="footer-middle-left">
            <div class="footer-dot"></div>
            <p>Follow Me</p>
        </div>
        <div class="footer-middle-right">
            {% for icon in social_icons %}
            <a href="{{ icon.icon_link }}">
                <img src="{{ icon.icon.url }}" alt="Social Icon">
            </a>
            {% endfor %}
        </div>
    </div>
    <div class="footer-bottom">
        <p>&copy; {{ footer.copyright_text }}</p>
    </div>
</footer>

portfolio/portfolio/templates/header.html
{% load static %}
<header>
    <nav>
        <div class="navbar-left">
            <a href="#home"><img src="{%static './icon/home.svg' %}" alt=""></a>
            <a href="#about"><img src="{% static './icon/education.svg' %}" alt=""></a>
            <a href="#myskill"><img src="{% static './icon/project.svg' %}" alt=""></a>
            <a href="#project"><img src="{% static './icon/product.svg' %}" alt=""></a>
        </div>
        <div class="navbar-right">
            <a href="{% url 'contact' %}">
                <img src="{% static './icon/mail4.svg' %}" alt="">
                <span class="hide-on-mobile">Contact Me</span>
            </a>
        </div>
    </nav>
</header>

portfolio/portfolio/templates/index.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}
{% load static %}
{% include 'header.html' %}

<main>
    <div id="home">
        <div class="hero-top">
            <div class="hero-top-left">
                <div class="dev-hero"></div>
                <h3>{{ hero.title }}</h3>
            </div>
            <div class="hero-top-right">
                <div class="active-hero"></div>
                <p>{{ hero.get_availability_display }}</p>
            </div>
        </div>
        <div class="hero-main">
            <div class="hero-main-left">
                <h1> I'm {{ hero.full_name }}</h1>
                <p>{{ hero.short_intro }} <span class="highlight">{{ hero.company_name }}</span>.</p>
                <div class="button-hero">
                    <a href="{{ hero.hireme_link }}" class="btn">Hire Me</a>
                    <a href="{{ hero.download_cv_button }}" class="btn btn-alt">Download CV</a>
                </div>
            </div>
            <div class="hero-main-right">
                {% if website.profile_picture %}
                <img src="{{ website.profile_picture.url }}" alt="Profile Picture" width="150">
                {% else %}
                <p>No profile picture available.</p>
                {% endif %}
            </div>
        </div>
        <div class="hero-bottom">
            <p>{{ hero.long_biography }}</p>
        </div>
    </div>

    <div id="about">
        <div class="education-top">
            <div class="education-top-left">
                <div class="dev-edu"></div>
                <h3>Education & Trining</h3>
            </div>
            <div class="education-top-right">
                <a href=""><span>View more</span> <i class="fas fa-arrow-right"></i></a>
            </div>
        </div>
        <div class="education-main">
            {% for edu in educations %}
            <div class="education-box">
                <div class="education-main-top-left">
                    <div class="main-edu"></div>
                    <h4>{{ edu.training_type }}</h4>
                </div>
                <div class="edu-box-main">
                    <p class="insti">{{ edu.institution_name }}</p>
                    <p class="subject"><strong>Subject: </strong>{{ edu.subject }}</p>
                    <p class="gpa"><strong>CGPA:</strong>{{ edu.cgpa|default:"Completed" }}</p>
                    <p class="pass-year"><strong>Year:</strong> {{ edu.year }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="myskill">
            <div class="myskill-top">
                <div class="myskill-top-left">
                    <div class="dev-edu"></div>
                    <h3>My Skills</h3>
                </div>
            </div>
            <div class="bottom-line"></div>
            {% for category in skill_categories %}
            <div class="myskill-top">
                <div class="myskill-top-left">
                    <div class="dev-edu"></div>
                    <h4>{{ category.name }}</h4>
                </div>
                <div class="skill-set">
                    {% for skill in category.skills.all %}
                    <img src="{{ skill.icon.url }}" alt="">
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="project">
            <div class="myskill-top">
                <div class="project-top-left">
                    <div class="dev-edu"></div>
                    <h3>My Projects</h3>
                </div>
            </div>
            <div class="project-bottom-line"></div>
            <div class="project-main">
                {% for project in projects %}
                <div class="project-card">
                    <div class="project-top">
                        <h3>{{ project.get_difficulty_level_display }}</h3>
                    </div>
                    <div class="project-middle">
                        <h3>{{ project.project_type }}</h3>
                        {% if project.logo %}
                        <img src="{{ project.logo.url }}" alt="{{ project.name }} Logo" width="100">
                        {% else %}
                        No logo available
                        {% endif %}
                        <h5>{{ project.get_status_display }}</h5>
                    </div>
                    <div class="project-bottom">
                        <a href="{{ project.project_link }}">View</a>
                        <h4>{{ project.start_date }}</h4>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</main>
{% include 'footer.html' %}
{% endblock %}